=== nzzdev/Q-election-executive/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "subtitle": {
      "type": "string"
    },
    "annotations": {
      "type": "string"
    },
    "isIntermediate": {
      "type": "boolean"
    },
    "majority": {
      "type": "number"
    },
    "candidates": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "party": {
            "type": "string"
          },
          "isPrevious": {
            "type": "boolean"
          },
          "votes": {
            "type": "number"
          },
          "status": {
            "enum": [
              "elected",
              "not elected",
              "undefined"
            ]
          },
          "color": {
            "type": "object",
            "properties": {
              "full": {
                "type": "object",
                "properties": {
                  "colorCode": {
                    "type": "string"
                  },
                  "classAttribute": {
                    "type": "string"
                  }
                }
              },
              "light": {
                "type": "object",
                "properties": {
                  "colorCode": {
                    "type": "string"
                  },
                  "classAttribute": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "image": {
            "type": "string"
          }
        }
      }
    },
    "notes": {
      "type": "string"
    },
    "sources": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "href": {
            "type": "string"
          },
          "validHref": {
            "type": "string"
          }
        }
      }
    }
  },
  "required": [
    "title"
  ]
}

=== nzzdev/Q-election-executive/resources/fixtures/data/results-no-majority-no-images.json
{
  "title": "FIXTURE: results - no majority - no images",
  "sources": [
    {
      "text": "NZZ",
      "link": {
        "url": "https://nzz.ch",
        "isValid": true
      }
    }
  ],
  "subtitle":
    "Möglichkeit zusätzliche Informationen als Untertitel zu erfassen",
  "notes":
    "Jemand musste Josef K. verleumdet haben, denn ohne dass er etwas Böses getan hätte, wurde er eines 'Morgens verhaftet.",
  "candidates": [
    {
      "name": "Hans Wurst",
      "color": {
        "full": {}
      },
      "isPrevious": true,
      "votes": 50000
    },
    {
      "name": "Maria Müller",
      "party": "SPD",
      "color": {
        "full": {}
      },
      "isPrevious": false,
      "votes": 120000
    },
    {
      "name": "Abdalá Bucaram",
      "party": "Fuerza Compromiso Social Social",
      "color": {
        "full": {}
      },
      "isPrevious": false,
      "votes": 90000
    },
    {
      "name": "Susann Salami",
      "party": "Die Linke",
      "color": {
        "full": {},
        "light": {}
      },
      "isPrevious": true,
      "votes": 130000
    }
  ]
}

=== nzzdev/Q-election-executive/resources/fixtures/data/no-results-no-majority-images.json
{
  "title": "FIXTURE: no results - no majority - images",
  "sources": [
    {
      "text": "NZZ",
      "link": {
        "url": "https://nzz.ch",
        "isValid": true
      }
    }
  ],
  "subtitle":
    "Möglichkeit zusätzliche Informationen als Untertitel zu erfassen",
  "notes":
    "Jemand musste Josef K. verleumdet haben, denn ohne dass er etwas Böses getan hätte, wurde er eines 'Morgens verhaftet.",
  "candidates": [
    {
      "name": "Hans Wurst",
      "color": {
        "full": {}
      },
      "picture": {
        "key": "2018/02/09/7d6fb4e4-e4a8-4e18-bb8f-36849ac9681c.png",
        "url":
          "https://nzz-q-assets-stage.s3.eu-west-1.amazonaws.com/2018/02/09/7d6fb4e4-e4a8-4e18-bb8f-36849ac9681c.png",
        "length": 5239,
        "width": 88,
        "height": 88
      },
      "isPrevious": true
    },
    {
      "name": "Maria Müller",
      "party": "SPD",
      "color": {
        "full": {}
      },
      "picture": {
        "key": "2018/02/09/3928b174-f2b3-4f45-b3f9-29d7aede0a06.png",
        "url":
          "https://nzz-q-assets-stage.s3.eu-west-1.amazonaws.com/2018/02/09/3928b174-f2b3-4f45-b3f9-29d7aede0a06.png",
        "length": 4615,
        "width": 88,
        "height": 88
      },
      "isPrevious": false
    },
    {
      "name": "Abdalá Bucaram",
      "party": "Fuerza Compromiso Social Social",
      "color": {
        "full": {}
      },
      "picture": {
        "key": "2018/02/09/2ea4a01c-0a28-4a4f-a643-3bd95a88a076.png",
        "url":
          "https://nzz-q-assets-stage.s3.eu-west-1.amazonaws.com/2018/02/09/2ea4a01c-0a28-4a4f-a643-3bd95a88a076.png",
        "length": 4615,
        "width": 88,
        "height": 88
      },
      "isPrevious": false
    },
    {
      "name": "Susann Salami",
      "party": "Die Linke",
      "color": {
        "full": {},
        "light": {}
      },
      "picture": {
        "key": "2018/02/09/c693d199-6900-4769-ad6a-03af483fa023.png",
        "url":
          "https://nzz-q-assets-stage.s3.eu-west-1.amazonaws.com/2018/02/09/c693d199-6900-4769-ad6a-03af483fa023.png",
        "length": 5239,
        "width": 88,
        "height": 88
      },
      "isPrevious": true
    }
  ]
}

=== nzzdev/Q-election-executive/resources/fixtures/data/results-majority-partly-images.json
{
  "title": "FIXTURE: results - majority - partly images",
  "sources": [
    {
      "text": "NZZ",
      "link": {
        "url": "https://nzz.ch",
        "isValid": true
      }
    }
  ],
  "subtitle":
    "Möglichkeit zusätzliche Informationen als Untertitel zu erfassen",
  "notes":
    "Jemand musste Josef K. verleumdet haben, denn ohne dass er etwas Böses getan hätte, wurde er eines 'Morgens verhaftet.",
  "majority": 20000,
  "candidates": [
    {
      "name": "Hans Wurst",
      "color": {
        "full": {}
      },
      "isPrevious": true,
      "votes": 50000
    },
    {
      "name": "Maria Müller",
      "party": "SPD",
      "color": {
        "full": {}
      },
      "isPrevious": false,
      "votes": 50000
    },
    {
      "name": "Abdalá Bucaram",
      "party": "Fuerza Compromiso Social Social",
      "color": {
        "full": {}
      },
      "picture": {
        "key": "2018/02/09/42ff8731-a6ea-4593-9297-d4e95f14162f.png",
        "url":
          "https://nzz-q-assets-stage.s3.eu-west-1.amazonaws.com/2018/02/09/42ff8731-a6ea-4593-9297-d4e95f14162f.png",
        "length": 4615,
        "width": 88,
        "height": 88
      },
      "isPrevious": false,
      "votes": 50000
    },
    {
      "name": "Susann Salami",
      "party": "Die Linke",
      "color": {
        "full": {},
        "light": {}
      },
      "picture": {
        "key": "2018/02/09/56f81f5a-7452-401a-a1b3-ddaaf5e53827.png",
        "url":
          "https://nzz-q-assets-stage.s3.eu-west-1.amazonaws.com/2018/02/09/56f81f5a-7452-401a-a1b3-ddaaf5e53827.png",
        "length": 5239,
        "width": 88,
        "height": 88
      },
      "isPrevious": true,
      "votes": 50000
    }
  ]
}

=== nzzdev/Q-election-executive/resources/fixtures/data/results-majority-no-images-status.json
{
  "title": "FIXTURE: results - majority - statuses - no images",
  "sources": [
    {
      "text": "NZZ",
      "link": {
        "url": "https://nzz.ch",
        "isValid": true
      }
    }
  ],
  "subtitle": "Möglichkeit zusätzliche Informationen als Untertitel zu erfassen",
  "notes": "Jemand musste Josef K. verleumdet haben, denn ohne dass er etwas Böses getan hätte, wurde er eines 'Morgens verhaftet.",
  "majority": 5000,
  "candidates": [
    {
      "name": "Hans Wurst",
      "color": {},
      "isPrevious": true,
      "status": "not elected",
      "votes": 50000
    },
    {
      "name": "Maria Müller",
      "party": "SPD",
      "color": {},
      "isPrevious": false,
      "status": "elected",
      "votes": 120000
    },
    {
      "name": "Abdalá Bucaram",
      "party": "Fuerza Compromiso Social Social Fuerza Compromiso Social Social",
      "color": {},
      "isPrevious": false,
      "status": "not elected",
      "votes": 90000
    },
    {
      "name": "Susann Anderegg",
      "party": "Die Linke",
      "color": {},
      "isPrevious": true,
      "status": "elected",
      "votes": 130000
    }
  ]
}

=== nzzdev/Q-election-executive/resources/fixtures/data/results-float-numbers-no-images-status.json
{
  "title": "FIXTURE: results - float numbers - statuses - no images",
  "sources": [
    {
      "text": "NZZ",
      "link": {
        "url": "https://nzz.ch",
        "isValid": true
      }
    }
  ],
  "subtitle": "Möglichkeit zusätzliche Informationen als Untertitel zu erfassen",
  "notes": "Jemand musste Josef K. verleumdet haben, denn ohne dass er etwas Böses getan hätte, wurde er eines 'Morgens verhaftet.",
  "majority": 5000,
  "candidates": [
    {
      "name": "Number one",
      "color": {},
      "isPrevious": true,
      "status": "not elected",
      "votes": 5135.34
    },
    {
      "name": "Number two",
      "party": "its a number too",
      "color": {},
      "isPrevious": false,
      "status": "elected",
      "votes": 123456.789
    }
  ]
}

=== nzzdev/Q-election-executive/resources/fixtures/data/before-v2.0.0/empty-candidate-name.json
{
  "title": "FIXTURE: empty candidate names",
  "sources": [
    {
      "text": "NZZ",
      "link": {
        "url": "https://nzz.ch",
        "isValid": true
      }
    }
  ],
  "subtitle":
    "Möglichkeit zusätzliche Informationen als Untertitel zu erfassen",
  "notes":
    "Jemand musste Josef K. verleumdet haben, denn ohne dass er etwas Böses getan hätte, wurde er eines 'Morgens verhaftet.",
  "majority": 100000,
  "candidates": [
    {
      "color": {
        "full": {}
      },
      "isPrevious": true,
      "votes": 50000
    },
    {
      "name": "Maria Müller",
      "party": "SPD",
      "color": {
        "full": {}
      },
      "isPrevious": false,
      "votes": 50000
    },
    {
      "name": "Abdalá Bucaram",
      "party": "Fuerza Compromiso Social Social",
      "color": {
        "full": {}
      },
      "picture": {
        "key": "2018/02/09/81402b8b-49af-4329-afe4-222402f696cf.png",
        "url":
          "https://nzz-q-assets-stage.s3.eu-west-1.amazonaws.com/2018/02/09/81402b8b-49af-4329-afe4-222402f696cf.png",
        "length": 5239,
        "width": 88,
        "height": 88
      },
      "isPrevious": false,
      "votes": 50000
    },
    {
      "name": "",
      "party": "Die Linke",
      "color": {
        "full": {},
        "light": {}
      },
      "picture": {
        "key": "2018/02/09/17cde314-b609-43df-a811-ca2828f3d545.png",
        "url":
          "https://nzz-q-assets-stage.s3.eu-west-1.amazonaws.com/2018/02/09/17cde314-b609-43df-a811-ca2828f3d545.png",
        "length": 4615,
        "width": 88,
        "height": 88
      },
      "isPrevious": true,
      "votes": 50000
    }
  ]
}
